# Używamy oficjalnego obrazu Nginx
FROM nginx:alpine

# Skopiuj zawartość lokalnego folderu (frontend) do katalogu html w kontenerze Nginx
COPY . /usr/share/nginx/html

# Expose port 80 (domyślny port Nginx)
EXPOSE 80
